package com.innerken.aadenprinterx.dataLayer.model

data class RestaurantInfoEntity(
    val adress1: String,
    val adress2: String,
    val bonLogo: String,
    val buffetLogo: String?,
    val buffetSetting: List<Any>,
    val callColor: String,
    val childRoundDishCount: String,
    val city: String,
    val emailAddress: String,
    val id: String,
    val inhalterLastName: String,
    val inhalterName: String,
    val inhalterTitle: String,
    val latitude: String,
    val logoUrl: String,
    val longitude: String,
    val maxDineTime: String,
    val name: String,
    val postCode: String,
    val roundDishCount: String,
    val roundTime: String,
    val state: String,
    val tableColor: String,
    val takeawayPriceModification: String,
    val taxNumber: String,
    val telephone: String,
    val totalRound: String,
)